import { HubSubcommandSpec } from "../../hub-data.js"

const spec: HubSubcommandSpec = {
  label: "ideation",
  description: "Iteratively refine premise, theme, setting, characters, and conflict before constitution — for when you don't have a solid idea yet",
  reminder: "Phase 0: Explore and refine raw ideas into a workable premise",
  phases: "0",
  detailedDescription: `# User Input: {userInput}

## Objective

Explore, expand, and iteratively refine raw creative ideas into a structured premise that is ready for the constitution phase. This phase exists BEFORE \`/kombinat manifest\` for users who:
- Don't have a solid premise yet
- Have a vague idea they want to flesh out
- Want to explore multiple angles before committing
- Need to develop theme, setting, characters, or conflict from scratch

## When to Use

- \`/kombinat guided\` detects no manifest AND the user has no clear premise
- The user explicitly asks to "brainstorm", "explore", "develop an idea", or "flesh out" a concept
- The user has fragments (a character, a setting, a theme) but no connecting premise
- The user wants to restructure an existing premise before proceeding to constitution

## Iterative Refinement Loop

This phase is inherently iterative. The user can return to it at any time via \`/kombinat ideation\` to further refine any aspect. Each iteration deepens one dimension.

### Dimensions

| Dimension | What it explores | Output artifact |
|-----------|------------------|-----------------|
| **Premise** | Core "what if" question, protagonist+goal+stakes+obstacle | \`./book/ideation/premise.md\` |
| **Theme** | What the work is *about* at a thematic level | \`./book/ideation/theme.md\` |
| **Setting** | World, time period, geography, social context, rules | \`./book/ideation/setting.md\` |
| **Characters** | Protagonist, antagonist, supporting cast, arcs, motivations | \`./book/ideation/characters.md\` |
| **Conflict** | Central conflict, internal/external layers, escalation path | \`./book/ideation/conflict.md\` |
| **Tone/Atmosphere** | Emotional register, mood, reader experience target | \`./book/ideation/tone.md\` |

## Execution Steps

### 1. Check Existing Ideation Cache

- Check \`./book/ideation/\` directory for existing artifacts
- If artifacts exist, load them and present current state
- Ask: "Which dimension would you like to refine?" using the \`question\` tool
- If no artifacts exist, start with premise exploration

### 2. Determine Focus Dimension

If \`{userInput}\` contains a dimension keyword, focus on that:

| Keyword | Dimension |
|---------|-----------|
| premise, idea, what-if, concept | Premise |
| theme, meaning, message | Theme |
| setting, world, location, geography | Setting |
| character, protagonist, antagonist, cast | Characters |
| conflict, tension, stakes, obstacle | Conflict |
| tone, mood, atmosphere, vibe | Tone/Atmosphere |

If no keyword detected, use the \`question\` tool:

\`\`\`
question: "Which dimension would you like to refine?"
header: "Ideation"
options:
  - label: "Premise", description: "Core what-if question, protagonist, goal, stakes, obstacle"
  - label: "Theme", description: "What the work is about at a thematic level"
  - label: "Setting", description: "World, time period, geography, social context"
  - label: "Characters", description: "Protagonist, antagonist, supporting cast, arcs"
  - label: "Conflict", description: "Central conflict, escalation, stakes"
  - label: "Tone", description: "Emotional register, mood, reader experience"
  - label: "All — Full Exploration", description: "Work through all dimensions sequentially"
\`\`\`

### 3. Refine Selected Dimension

Use divergent-then-convergent refinement:

**Divergent (expand):**
- Generate 3-5 distinct possibilities for the dimension
- Ask clarifying questions about what resonates with the user
- Use the \`question\` tool for each branching decision
- Explore contradictions, tensions, and unexpected angles

**Convergent (sharpen):**
- Help the user select the strongest option
- Stress-test it against the existing artifacts (if any)
- Check for consistency with other dimensions already developed
- Ask: "Does this feel right? Should we iterate further or move to another dimension?"

### 4. Cache the Output

Save the refined dimension to \`./book/ideation/[dimension].md\`:

\`\`\`markdown
# [Dimension Name] — Refinement [N]

*Generated by /kombinat ideation — [date]*

## Current Version

[The refined content for this dimension]

## Alternatives Considered

[Brief notes on rejected alternatives — preserved for future reference]

## Connections

- Theme → [how this connects to theme, if theme.md exists]
- Setting → [how this connects to setting, if setting.md exists]
- Characters → [how this connects to characters, if characters.md exists]
- Conflict → [how this connects to conflict, if conflict.md exists]

## Next Steps

- [Suggested next dimension to refine, or "Ready for /kombinat manifest"]
\`\`\`

### 5. Cross-Dimension Consistency Check

After caching, if 2+ dimension artifacts exist:
- Check for contradictions between dimensions
- Flag any tensions (e.g., dark tone with a light-hearted setting)
- Suggest how to resolve or lean into the tension

### 6. Handoff

After each refinement cycle, ask using the \`question\` tool:

\`\`\`
question: "What would you like to do next?"
header: "Ideation"
options:
  - label: "Refine another dimension", description: "Continue iterating on a different aspect"
  - label: "Refine this dimension further", description: "Go deeper on the same dimension"
  - label: "Ready for manifest", description: "Proceed to /kombinat manifest to establish governing principles"
  - label: "Save and exit", description: "Cache current state and return later"
\`\`\`

If "Ready for manifest": Check that at minimum \`premise.md\` and \`theme.md\` exist. If not, warn the user. If yes, run \`/kombinat manifest\` (call hubMenu route for \`manifest\`).

## Track Adaptation

| Track | Ideation focus |
|-------|---------------|
| Fiction | Premise, characters, setting, conflict, theme, tone |
| Non-fiction | Thesis, argument structure, audience, scope, methodology |
| Mixed | Both — creative premise + intellectual thesis |

For non-fiction, the dimensions map to:
- Premise → Thesis statement
- Theme → Central argument
- Setting → Scope and context
- Characters → Key voices/perspectives
- Conflict → Counterarguments and tensions
- Tone → Academic register vs accessibility

## File Layout

\`\`\`
./book/ideation/
├── premise.md       # Core premise / thesis
├── theme.md         # Thematic statement / argument
├── setting.md       # World / scope
├── characters.md    # Cast / perspectives
├── conflict.md     # Central conflict / tensions
├── tone.md          # Emotional register
└── _index.json     # Machine-readable manifest of all artifacts
\`\`\`

The \`_index.json\` file tracks:
\`\`\`json
{
  "dimensions": {
    "premise": { "version": 3, "lastUpdated": "2026-01-15T10:30:00Z", "ready": true },
    "theme": { "version": 2, "lastUpdated": "2026-01-15T10:45:00Z", "ready": true },
    "setting": { "version": 1, "lastUpdated": "2026-01-14T14:00:00Z", "ready": true },
    "characters": { "version": 0, "ready": false },
    "conflict": { "version": 0, "ready": false },
    "tone": { "version": 1, "lastUpdated": "2026-01-14T14:30:00Z", "ready": true }
  },
  "readyForConstitution": false,
  "lastRefinement": "2026-01-15T10:45:00Z"
}
\`\`\`

\`readyForConstitution\` becomes true when \`premise\` and \`theme\` are both \`ready\`.

## Supplement Skills

| Skill | Purpose |
|-------|---------|
| \`idea-refine\` | Divergent/convergent iteration methodology |
| \`graph-thinking\` | Map relationships between dimensions |
| \`deep-thinker\` | Break down complex creative problems |

Load these skills on demand when the user's input suggests they'd help.

## Warnings

- Do NOT skip to constitution without at least a premise — the constitution needs a thematic statement to anchor it
- Do NOT treat ideation artifacts as canon — they are exploratory and mutable
- Do NOT overwrite a dimension artifact without offering to view the current version first
- The user can return to this phase at any time via \`/kombinat ideation\` — it is NOT a one-time gate
`,
  tools: ["loadSkill", "question", "bash", "write", "read"],
  relatedSkills: ["idea-refine", "graph-thinking"],
  examples: [
    { input: "/kombinat ideation", approach: "Loads existing ideation cache, presents dimension menu for refinement" },
    { input: "/kombinat ideation premise", approach: "Focuses on premise dimension — generates alternatives, helps user select, caches to ./book/ideation/premise.md" },
    { input: "/kombinat ideation characters", approach: "Focuses on character dimension — develops protagonist, antagonist, supporting cast" },
    { input: "/kombinat ideation all", approach: "Sequential full exploration through all dimensions" },
  ],
  warnings: [
    "Do not skip to constitution without at minimum a premise and theme",
    "Ideation artifacts are exploratory — they can be revised at any time by returning to this phase",
    "Always check ./book/ideation/ for existing artifacts before starting fresh",
  ]
}

export default spec